### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by cgzones**
* Add option to run Lintian after build
* Add option to build via ccache to speed up repeated builds
* Use apt cache to speed up package installations
* Support DEB_BUILD_PROFILES
* Add support for unprivileged podman
* Several performance and output improvements

### CODE REVIEW

**Comment by joelpurra** [comment]
Commenting to confirm that this pull request works well with rootless/unprivileged [`podman`](https://github.com/containers/podman). Tested building a package using Ubuntu 22.04, as well as 23.04 (copy `Dockerfile-ubuntu-22.04`, change version number in tag). Am not a regular `docker-deb-builder` user, so cannot comment on other changes.

**Comment by voltagex** [comment]
I'm not sure if it's your patch or my docker version but I needed to use the following patch to make this work

```
diff --git a/build b/build
index 9ad7e93..e495404 100755
--- a/build
+++ b/build
@@ -113,7 +113,7 @@ if [[ "$depdir" ]]; then
     docker_args+="-v $(abspath "$depdir"):/dependencies:ro "
 fi

-docker_args+="-v $(abspath "$srcdir"):/build/source:O "
+docker_args+="-v $(abspath "$srcdir"):/build/source "
 docker_args+="-v $(abspath "$outdir"):/output "
 docker_args+="-v $(cd "$PROG_DIR"; pwd)/build-helper.sh:/build-helper.sh:ro "
 docker_args+="--mount type=tmpfs,tmpfs-size=4G,destination=/tmp "
```

Without this the docker command/s errored out as "O" was not a recognised option for the volume.

**Comment by cgzones** [comment]
> I'm not sure if it's your patch or my docker version but I needed to use the following patch to make this work
> 
> ...
> 
> Without this the docker command/s errored out as "O" was not a recognised option for the volume.

The overlay volume option seems to be a podman only feature, dropped that change.

**Comment by tsaarni** [comment]
Hi @cgzones! I have looked at your work and you have really done a lot of improvements here 🙏 

Like I have put in the project description, I intended this project originally as a tutorial.  Back then I had some one-off package that I wanted to build myself and came up with the idea to upload it as an example for others that might be looking to do the same.  I thought this project as something that anyone could go through quickly and understand fully - just a screenful or two of scripts. I would prefer keeping this scope. I think I would have bit tough times testing and supporting full-featured script for a production use case 😅

That said, if you don't mind, would you like to host another project with all your great improvements (ccache, lintian, podman, tmpfs, ansi-color highlights) and I would point that from this project as improved version, better suited for production?

**Comment by cgzones** [comment]
Created a renamed fork at https://github.com/cgzones/container-deb-builder/.
Thanks for starting the project in the first place!

**Comment by tsaarni** [comment]
Cool! Thanks for understanding @cgzones. I linked your project here, on the [Overview chapter](https://github.com/tsaarni/docker-deb-builder/blob/master/README.md#overview)

**Pull request closed without merging**
